language: C++

matrix:
  include:
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: MATRIX_EVAL="CXX=clang++"
      
    - os: linux
      dist: trusty
      compiler: clang
      env: MATRIX_EVAL="CXX=clang++-4.0"

script: 
    - make -j9

before_install:
  - eval "${MATRIX_EVAL}"